services:
  test_db_mysql:
    image: mysql:5.7
    container_name: messenger_test_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password_test
      MYSQL_DATABASE: messenger_test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
