"""chat_participant_add_chat_name

Revision ID: bd95aa5fe9ce
Revises: 423f34e174a4
Create Date: 2025-07-03 10:49:49.498585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bd95aa5fe9ce'
down_revision: Union[str, None] = '423f34e174a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_participant',
                  sa.Column('chat_name', sa.String(length=50), nullable=True))

    op.execute("""
            UPDATE chat_participant cp
            JOIN chat c ON cp.chat_id = c.chat_id
            SET cp.chat_name = c.name
            WHERE c.is_group = TRUE
        """)

    op.execute("""
    UPDATE chat_participant cp
    JOIN chat_participant other_cp ON cp.chat_id = other_cp.chat_id AND cp.user_id != other_cp.user_id
    JOIN user u ON other_cp.user_id = u.user_id
    JOIN chat c ON cp.chat_id = c.chat_id
    SET cp.chat_name = u.display_name
    WHERE c.is_group = FALSE
    """)

    op.alter_column('chat_participant', 'chat_name', existing_type=sa.String(50), nullable=False)

    op.drop_index('ix_chat_name', table_name='chat')
    op.drop_column('chat', 'name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_participant', 'chat_name')
    op.add_column('chat', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.create_index('ix_chat_name', 'chat', ['name'], unique=False)
    # ### end Alembic commands ###
