name: CI Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.10.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          
      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.10.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx pytest-asyncio

      - name: Run tests with pytest
        run: |
          pytest

