name: CI Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.10.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          
      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics

  test:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      mysql-test-db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root_password_test
          MYSQL_DATABASE: messenger_test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      MYSQL_HOST: 127.0.0.1
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
      MYSQL_DATABASE: messenger_test_db

      TEST_DB_USER: test_user
      TEST_DB_PASSWORD: test_password
      TEST_DB_NAME: messenger_test_db
      TEST_DB_HOST: 127.0.0.1
      TEST_DB_PORT: 3306
      DATABASE_URL: mysql+aiomysql://$TEST_DB_USER:$TEST_DB_PASSWORD@$TEST_DB_HOST:$TEST_DB_PORT/$TEST_DB_NAME

      SECRET_KEY: ci_test_secret_key
      SQLALCHEMY_ECHO: False
      DEBUG: False

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.10.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'

      - name: Wait for MySQL Service to be ready
        run: |
          echo "Waiting for MySQL..."
          until mysqladmin ping -h $TEST_DB_HOST -P $TEST_DB_PORT -u $TEST_DB_USER -p$TEST_DB_PASSWORD --silent; do
            echo "MySQL is unavailable - sleeping"
            sleep 1;
          done
          echo "MySQL is up - executing command"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade pytest httpx pytest-asyncio aiomysql

      - name: Run tests with pytest
        run: |
          pytest
